# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-27 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20240127_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 6, 18, 12, 393718, tzinfo=utc)),
        ),
    ]
